fixtures:
  forge_modules:
    apt: puppetlabs/apt
    cron_core: puppetlabs/cron_core
    concat: puppetlabs/concat
    postgresql: puppetlabs/postgresql
    sshkeys_core: puppetlabs/sshkeys_core
    stdlib: puppetlabs/stdlib
    systemd: puppet/systemd
    yumrepo_core: puppetlabs/yumrepo_core
